// Code generated by goyacc -v grammar/y.output -o grammar/block_query.go grammar/block_query.y. DO NOT EDIT.

//line grammar/block_query.y:6
package grammar

import __yyfmt__ "fmt"

//line grammar/block_query.y:6
import (
	// "strconv"
	"github.com/auser/block_query/value"
)

//line grammar/block_query.y:15
type yySymType struct {
	yys         int
	program     []Statement
	statement   Statement
	queryexpr   QueryExpression
	queryexprs  []QueryExpression
	expression  Expression
	expressions []Expression
	identifier  Identifier
	variable    Variable
	variables   []Variable
	token       Token
	table       Table
}

const LEX_ERROR = 57346
const recursive = 57347
const IDENTIFIER = 57348
const STRING = 57349
const INTEGER = 57350
const FLOAT = 57351
const BOOLEAN = 57352
const TERNARY = 57353
const DATETIME = 57354
const VARIABLE = 57355
const FLAG = 57356
const SELECT = 57357
const FROM = 57358
const WITH = 57359
const ORDER = 57360
const BY = 57361
const LIMIT = 57362
const OFFSET = 57363
const PARTITION = 57364
const TABLES = 57365
const VIEWS = 57366
const CURSORS = 57367
const FUNCTIONS = 57368
const FUNCTION_NTH = 57369
const FUNCTION_WITH_INS = 57370
const AND = 57371
const OR = 57372
const NOT = 57373
const ASC = 57374
const DESC = 57375
const FIRST = 57376
const LAST = 57377
const ERROR = 57378
const UMINUS = 57379
const COUNT = 57380
const LISTAGG = 57381
const ROWS = 57382
const AGGREGATE_FUNCTION = 57383
const ANALYTIC_FUNCTION = 57384
const NULLS = 57385
const NULL = 57386
const IN = 57387
const EXISTS = 57388
const TIES = 57389
const FIELDS = 57390
const ALL = 57391
const AS = 57392
const COMPARISON_OP = 57393
const STRING_OP = 57394
const PERCENT = 57395
const STDIN = 57396
const SUBSTITUTION_OP = 57397
const DISTINCT = 57398
const UNION = 57399
const EXCEPT = 57400
const INTERSECT = 57401
const CROSS = 57402
const FULL = 57403
const NATURAL = 57404
const JOIN = 57405
const IS = 57406
const BETWEEN = 57407
const LIKE = 57408
const UPLUS = 57409

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEX_ERROR",
	"recursive",
	"IDENTIFIER",
	"STRING",
	"INTEGER",
	"FLOAT",
	"BOOLEAN",
	"TERNARY",
	"DATETIME",
	"VARIABLE",
	"FLAG",
	"SELECT",
	"FROM",
	"WITH",
	"ORDER",
	"BY",
	"LIMIT",
	"OFFSET",
	"PARTITION",
	"TABLES",
	"VIEWS",
	"CURSORS",
	"FUNCTIONS",
	"FUNCTION_NTH",
	"FUNCTION_WITH_INS",
	"AND",
	"OR",
	"NOT",
	"ASC",
	"DESC",
	"FIRST",
	"LAST",
	"ERROR",
	"UMINUS",
	"COUNT",
	"LISTAGG",
	"ROWS",
	"AGGREGATE_FUNCTION",
	"ANALYTIC_FUNCTION",
	"NULLS",
	"NULL",
	"IN",
	"EXISTS",
	"TIES",
	"FIELDS",
	"ALL",
	"AS",
	"COMPARISON_OP",
	"STRING_OP",
	"PERCENT",
	"STDIN",
	"SUBSTITUTION_OP",
	"DISTINCT",
	"';'",
	"'*'",
	"'='",
	"'-'",
	"'+'",
	"'!'",
	"'('",
	"')'",
	"UNION",
	"EXCEPT",
	"INTERSECT",
	"CROSS",
	"FULL",
	"NATURAL",
	"JOIN",
	"IS",
	"BETWEEN",
	"LIKE",
	"'/'",
	"'%'",
	"UPLUS",
	"','",
	"'.'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line grammar/block_query.y:723
func SetDebugLevel(level int, verbose bool) {
	yyDebug = level
	yyErrorVerbose = verbose
}

func Parse(s string, sourceFile string) ([]Statement, error) {
	l := new(Lexer)
	l.Init(s, sourceFile)
	yyParse(l)
	return l.program, l.err
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 64,
	51, 67,
	59, 67,
	-2, 125,
	-1, 159,
	45, 0,
	51, 0,
	59, 0,
	-2, 72,
	-1, 160,
	45, 0,
	51, 0,
	59, 0,
	-2, 74,
	-1, 210,
	1, 61,
	16, 61,
	20, 61,
	21, 61,
	32, 61,
	33, 61,
	43, 61,
	50, 61,
	57, 61,
	64, 61,
	78, 61,
	-2, 97,
	-1, 211,
	1, 62,
	16, 62,
	20, 62,
	21, 62,
	32, 62,
	33, 62,
	43, 62,
	50, 62,
	57, 62,
	64, 62,
	78, 62,
	-2, 98,
}

const yyPrivate = 57344

const yyLast = 772

var yyAct = [...]int{

	106, 4, 93, 150, 176, 178, 56, 82, 58, 95,
	64, 4, 44, 177, 140, 118, 53, 117, 116, 27,
	193, 51, 71, 19, 143, 122, 121, 115, 71, 50,
	90, 145, 119, 120, 99, 217, 109, 126, 103, 214,
	127, 114, 26, 213, 212, 211, 210, 112, 111, 209,
	104, 51, 107, 127, 118, 113, 117, 116, 111, 50,
	175, 122, 121, 115, 118, 206, 117, 116, 118, 196,
	215, 119, 120, 192, 174, 173, 124, 114, 154, 153,
	162, 119, 120, 112, 111, 119, 120, 101, 149, 144,
	118, 113, 117, 116, 134, 132, 135, 131, 128, 10,
	102, 20, 123, 133, 207, 151, 51, 119, 120, 110,
	174, 155, 71, 157, 50, 45, 152, 187, 164, 190,
	138, 91, 161, 204, 205, 163, 156, 179, 147, 148,
	180, 24, 14, 25, 23, 9, 13, 7, 142, 18,
	184, 185, 182, 163, 163, 183, 9, 57, 71, 12,
	191, 1, 92, 98, 99, 189, 186, 89, 188, 100,
	6, 22, 21, 16, 105, 47, 11, 46, 124, 49,
	69, 68, 194, 66, 63, 163, 67, 76, 62, 61,
	195, 203, 197, 65, 78, 146, 97, 198, 200, 199,
	96, 60, 54, 201, 55, 202, 151, 208, 125, 15,
	5, 17, 8, 3, 2, 0, 0, 129, 130, 0,
	0, 0, 136, 137, 0, 0, 216, 0, 0, 139,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 57, 0, 158,
	159, 160, 0, 0, 165, 166, 167, 168, 169, 170,
	171, 172, 0, 0, 0, 0, 0, 28, 73, 74,
	75, 0, 87, 77, 86, 0, 9, 0, 7, 0,
	0, 0, 0, 98, 31, 32, 33, 34, 41, 42,
	0, 0, 84, 0, 0, 0, 0, 43, 0, 94,
	38, 35, 81, 40, 30, 88, 0, 83, 29, 36,
	28, 73, 74, 75, 0, 87, 77, 86, 0, 0,
	0, 79, 80, 85, 70, 0, 0, 31, 32, 33,
	34, 41, 42, 0, 0, 84, 0, 0, 0, 0,
	43, 0, 94, 38, 35, 81, 40, 30, 88, 0,
	83, 29, 36, 28, 73, 74, 75, 0, 87, 77,
	86, 0, 59, 0, 79, 80, 85, 70, 0, 0,
	31, 32, 33, 34, 41, 42, 0, 0, 84, 0,
	0, 0, 0, 43, 0, 94, 38, 35, 81, 40,
	30, 88, 0, 83, 29, 36, 0, 0, 0, 28,
	73, 74, 75, 20, 87, 77, 86, 79, 80, 85,
	70, 0, 0, 0, 0, 0, 31, 32, 33, 34,
	41, 42, 0, 0, 84, 0, 0, 0, 0, 43,
	0, 72, 38, 35, 81, 40, 30, 88, 0, 83,
	29, 36, 28, 73, 74, 75, 0, 87, 77, 86,
	0, 59, 0, 79, 80, 85, 70, 0, 0, 31,
	32, 33, 34, 41, 42, 0, 0, 84, 0, 0,
	0, 0, 43, 0, 94, 38, 35, 81, 40, 30,
	88, 0, 83, 29, 36, 28, 73, 74, 75, 0,
	87, 77, 86, 0, 0, 0, 79, 80, 85, 70,
	0, 0, 31, 32, 33, 34, 41, 42, 0, 0,
	84, 0, 0, 0, 0, 43, 142, 72, 38, 35,
	81, 40, 30, 88, 0, 83, 29, 36, 122, 121,
	115, 0, 122, 121, 115, 0, 0, 0, 0, 79,
	80, 85, 70, 0, 114, 0, 0, 0, 114, 0,
	112, 111, 141, 0, 112, 111, 115, 118, 113, 117,
	116, 118, 113, 117, 116, 122, 0, 115, 0, 0,
	114, 0, 0, 0, 119, 120, 112, 111, 119, 120,
	0, 114, 0, 118, 113, 117, 116, 112, 111, 0,
	0, 0, 0, 0, 118, 113, 117, 116, 28, 0,
	119, 120, 0, 0, 0, 0, 0, 9, 0, 7,
	0, 119, 120, 0, 0, 31, 32, 33, 34, 41,
	42, 0, 0, 0, 0, 0, 0, 0, 43, 0,
	37, 38, 35, 39, 40, 30, 0, 0, 0, 29,
	36, 28, 0, 0, 0, 0, 52, 0, 0, 0,
	0, 0, 0, 0, 0, 48, 0, 0, 31, 32,
	33, 34, 41, 42, 0, 0, 0, 0, 0, 0,
	0, 43, 0, 37, 38, 35, 39, 40, 30, 0,
	0, 0, 29, 36, 28, 0, 0, 0, 0, 52,
	0, 0, 0, 0, 0, 0, 0, 0, 48, 0,
	0, 31, 32, 33, 34, 41, 42, 0, 0, 0,
	0, 0, 0, 28, 43, 181, 37, 38, 35, 39,
	40, 30, 0, 0, 0, 29, 36, 0, 108, 0,
	31, 32, 33, 34, 41, 42, 0, 0, 0, 28,
	0, 0, 0, 43, 0, 37, 38, 35, 39, 40,
	30, 0, 0, 0, 29, 36, 31, 32, 33, 34,
	41, 42, 0, 0, 0, 0, 0, 0, 0, 43,
	0, 37, 38, 35, 39, 40, 30, 0, 0, 0,
	29, 36,
}
var yyPact = [...]int{

	120, -1000, 42, -1000, -1000, 131, 118, 158, 123, 45,
	120, 118, 111, 114, -1000, -36, 723, -1000, 625, 383,
	-1000, -1000, 111, 100, 426, 469, 158, 37, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -40, -1000, 723, 582, 668,
	-1000, -1000, -1000, -1000, -42, 59, -1000, 493, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 47, -1000,
	251, -26, 35, -1000, -1000, -1000, -1000, -1000, -1000, 426,
	426, 34, 44, 33, 426, 426, -1000, -1000, -1000, 100,
	-1000, 426, 489, -39, 26, -1000, -47, 96, 493, -1000,
	-1000, 25, 723, 625, -1000, 15, 14, -1000, 723, 383,
	723, 426, 426, 426, 17, 73, 426, 426, 426, 426,
	426, 426, 426, 426, 11, -4, 337, 697, 45, -1000,
	-1000, 45, 17, 17, -1000, 120, 515, -1000, -1000, 493,
	-1000, 121, 70, 45, 45, 469, 76, -1000, -1000, 120,
	9, -58, -1000, -1000, -1000, -1000, -1000, -1000, -43, 6,
	6, -1000, 251, -1000, 17, 10, 10, -1000, -1000, -1000,
	526, 515, 493, -1000, 426, -1000, 5, 426, -1000, 32,
	-1000, -1000, 294, 426, -1000, -1000, -1000, -1000, 294, -1000,
	89, 1, 54, 723, -1000, -1000, -1000, -15, -18, -19,
	-20, -21, -25, -1000, -1000, -1000, -1000, 7, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 120, -29, -1000,
}
var yyPgo = [...]int{

	0, 151, 204, 203, 0, 202, 201, 12, 3, 115,
	200, 199, 132, 160, 149, 134, 14, 30, 194, 192,
	16, 192, 191, 127, 5, 6, 4, 9, 190, 7,
	190, 186, 185, 184, 183, 181, 179, 178, 177, 176,
	174, 10, 173, 171, 171, 170, 169, 167, 165, 8,
	2, 13, 165,
}
var yyR1 = [...]int{

	0, 1, 1, 1, 2, 3, 4, 4, 13, 5,
	6, 14, 14, 27, 27, 28, 28, 31, 31, 32,
	32, 32, 35, 35, 15, 15, 15, 16, 16, 17,
	17, 18, 18, 19, 19, 19, 20, 20, 7, 7,
	9, 9, 9, 9, 46, 46, 47, 47, 47, 48,
	10, 10, 11, 11, 12, 12, 8, 8, 24, 24,
	49, 49, 49, 26, 26, 25, 29, 29, 30, 30,
	41, 40, 42, 42, 42, 42, 42, 42, 42, 21,
	21, 22, 22, 22, 37, 37, 37, 37, 37, 37,
	37, 39, 39, 39, 39, 34, 34, 34, 34, 50,
	50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
	50, 50, 50, 50, 50, 33, 43, 44, 44, 45,
	38, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 36, 36, 36, 36, 36, 36, 51, 51,
	52,
}
var yyR2 = [...]int{

	0, 0, 1, 3, 1, 1, 5, 4, 2, 3,
	2, 0, 3, 1, 3, 2, 4, 1, 1, 0,
	1, 1, 1, 1, 0, 3, 4, 0, 2, 0,
	2, 1, 1, 1, 3, 1, 1, 3, 1, 3,
	1, 1, 2, 3, 1, 1, 1, 2, 3, 1,
	0, 2, 6, 9, 1, 3, 1, 3, 1, 3,
	4, 5, 5, 0, 1, 1, 3, 1, 1, 3,
	3, 3, 3, 3, 3, 3, 3, 4, 2, 1,
	3, 1, 3, 3, 3, 3, 3, 3, 3, 2,
	2, 3, 3, 2, 2, 5, 5, 5, 5, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 3, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 1, 1, 1, 1, 1, 1, 0, 1,
	1,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, -4, -10, -13, 17, -5, 15,
	57, -13, -14, 18, -12, -11, 5, -6, 16, -51,
	56, -1, -14, -15, 20, 19, 78, -50, 6, 47,
	43, 23, 24, 25, 26, 40, 48, 38, 39, 41,
	42, 27, 28, 36, -7, -9, -47, -48, 63, -46,
	-41, -50, 54, -20, -19, -18, -25, -23, -49, 58,
	-22, -36, -37, -40, -41, -34, -42, -39, -43, -45,
	63, -50, 38, 7, 8, 9, -38, 12, -33, 60,
	61, 41, -29, 46, 31, 62, 13, 11, 44, -15,
	-17, 21, -23, -50, 38, -27, -28, -31, -23, -49,
	-12, 50, 63, 78, -50, -9, -4, -50, 50, 78,
	50, 52, 51, 59, 45, 31, 61, 60, 58, 75,
	76, 30, 29, 55, -24, -23, 63, 79, 63, -23,
	-23, 63, 51, 59, -41, 63, -23, -23, -17, -23,
	-16, 53, 17, 63, 63, 78, -32, 32, 33, 63,
	-8, -50, -7, 64, 64, -50, -20, -50, -23, -23,
	-23, -29, 63, -41, 45, -23, -23, -23, -23, -23,
	-23, -23, -23, 64, 78, 64, -26, -51, -24, -23,
	-50, 8, -51, -51, -29, -29, -16, 47, -51, -27,
	43, -4, 64, 78, -29, -24, 64, -26, -26, -25,
	-26, -26, -25, -35, 34, 35, 64, 50, -8, 64,
	64, 64, 64, 64, 64, 63, -4, 64,
}
var yyDef = [...]int{

	1, -2, 2, 4, 5, 0, 11, 0, 0, 138,
	1, 11, 24, 0, 51, 54, 0, 8, 0, 0,
	139, 3, 24, 29, 0, 0, 0, 0, 99, 100,
	101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
	111, 112, 113, 114, 10, 38, 40, 41, 0, 46,
	49, 44, 45, 9, 36, 33, 35, 31, 32, 65,
	121, 122, 123, 124, -2, 126, 127, 128, 129, 130,
	0, 81, 108, 132, 133, 134, 135, 136, 137, 0,
	0, 110, 0, 0, 0, 0, 116, 120, 115, 29,
	7, 0, 27, 81, 108, 12, 13, 19, 17, 18,
	55, 0, 0, 0, 42, 0, 0, 47, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 63, 0, 138, 89,
	90, 138, 0, 0, 78, 0, 93, 94, 6, 30,
	25, 27, 0, 138, 138, 0, 15, 20, 21, 0,
	0, 56, 39, 43, 70, 48, 37, 34, 71, -2,
	-2, 76, 0, 67, 0, 84, 85, 86, 87, 88,
	91, 92, 119, 66, 0, 131, 0, 63, 64, 58,
	82, 83, 63, 63, 73, 75, 26, 28, 63, 14,
	0, 0, 0, 0, 77, 59, 60, 0, 0, 0,
	0, 0, 0, 16, 22, 23, 52, 0, 57, 95,
	-2, -2, 96, 97, 98, 0, 0, 53,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 62, 3, 3, 3, 76, 3, 3,
	63, 64, 58, 61, 78, 60, 79, 75, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 57,
	3, 59,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 65, 66, 67, 68, 69,
	70, 71, 72, 73, 74, 77,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line grammar/block_query.y:133
		{
			yyVAL.program = nil
			yylex.(*Lexer).program = yyVAL.program
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:138
		{
			yyVAL.program = []Statement{yyDollar[1].statement}
			yylex.(*Lexer).program = yyVAL.program
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:143
		{
			yyVAL.program = append([]Statement{yyDollar[1].statement}, yyDollar[3].program...)
			yylex.(*Lexer).program = yyVAL.program
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:151
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:157
		{
			yyVAL.statement = yyDollar[1].queryexpr
		}
	case 6:
		yyDollar = yyS[yypt-5 : yypt+1]
		//line grammar/block_query.y:162
		{
			yyVAL.queryexpr = SelectQuery{
				WithClause:    yyDollar[1].queryexpr,
				SelectEntity:  yyDollar[2].queryexpr,
				OrderByClause: yyDollar[3].queryexpr,
				LimitClause:   yyDollar[4].queryexpr,
				OffsetClause:  yyDollar[5].queryexpr,
			}
		}
	case 7:
		yyDollar = yyS[yypt-4 : yypt+1]
		//line grammar/block_query.y:172
		{
			yyVAL.queryexpr = SelectQuery{
				SelectEntity:  yyDollar[1].queryexpr,
				OrderByClause: yyDollar[2].queryexpr,
				LimitClause:   yyDollar[3].queryexpr,
				OffsetClause:  yyDollar[4].queryexpr,
			}
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:184
		{
			yyVAL.queryexpr = SelectEntity{
				SelectClause: yyDollar[1].queryexpr,
				FromClause:   yyDollar[2].queryexpr,
			}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:194
		{
			yyVAL.queryexpr = SelectClause{
				BaseExpr: NewBaseExpr(yyDollar[1].token), Select: yyDollar[1].token.Literal, Distinct: yyDollar[2].token, Fields: yyDollar[3].queryexprs}
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:201
		{
			yyVAL.queryexpr = FromClause{From: yyDollar[1].token.Literal, Tables: yyDollar[2].queryexprs}
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line grammar/block_query.y:207
		{
			yyVAL.queryexpr = nil
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:209
		{
			yyVAL.queryexpr = OrderByClause{OrderBy: yyDollar[1].token.Literal + " " + yyDollar[2].token.Literal, Items: yyDollar[3].queryexprs}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:214
		{
			yyVAL.queryexprs = []QueryExpression{yyDollar[1].queryexpr}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:215
		{
			yyVAL.queryexprs = append([]QueryExpression{yyDollar[1].queryexpr}, yyDollar[3].queryexprs...)
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:219
		{
			yyVAL.queryexpr = OrderItem{Value: yyDollar[1].queryexpr, Direction: yyDollar[2].token}
		}
	case 16:
		yyDollar = yyS[yypt-4 : yypt+1]
		//line grammar/block_query.y:221
		{
			yyVAL.queryexpr = OrderItem{Value: yyDollar[1].queryexpr, Direction: yyDollar[2].token, Nulls: yyDollar[3].token.Literal, Position: yyDollar[4].token}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:227
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:228
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 19:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line grammar/block_query.y:232
		{
			yyVAL.token = Token{}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:233
		{
			yyVAL.token = yyDollar[1].token
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:234
		{
			yyVAL.token = yyDollar[1].token
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:238
		{
			yyVAL.token = yyDollar[1].token
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:239
		{
			yyVAL.token = yyDollar[1].token
		}
	case 24:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line grammar/block_query.y:243
		{
			yyVAL.queryexpr = nil
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:245
		{
			yyVAL.queryexpr = LimitClause{BaseExpr: NewBaseExpr(yyDollar[1].token), Limit: yyDollar[1].token.Literal, Value: yyDollar[2].queryexpr, With: yyDollar[3].queryexpr}
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
		//line grammar/block_query.y:249
		{
			yyVAL.queryexpr = LimitClause{BaseExpr: NewBaseExpr(yyDollar[1].token), Limit: yyDollar[1].token.Literal, Value: yyDollar[2].queryexpr, Percent: yyDollar[3].token.Literal, With: yyDollar[4].queryexpr}
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line grammar/block_query.y:256
		{
			yyVAL.queryexpr = nil
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:260
		{
			yyVAL.queryexpr = LimitWith{With: yyDollar[1].token.Literal, Type: yyDollar[2].token}
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line grammar/block_query.y:265
		{
			yyVAL.queryexpr = nil
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:267
		{
			yyVAL.queryexpr = OffsetClause{BaseExpr: NewBaseExpr(yyDollar[1].token), Offset: yyDollar[1].token.Literal, Value: yyDollar[2].queryexpr}
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:273
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:274
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:277
		{
			yyVAL.queryexpr = Field{Object: yyDollar[1].queryexpr}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:279
		{
			yyVAL.queryexpr = Field{Object: yyDollar[1].queryexpr, As: yyDollar[2].token.Literal, Alias: yyDollar[3].identifier}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:282
		{
			yyVAL.queryexpr = Field{Object: yyDollar[1].queryexpr}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:286
		{
			yyVAL.queryexprs = []QueryExpression{yyDollar[1].queryexpr}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:287
		{
			yyVAL.queryexprs = append([]QueryExpression{yyDollar[1].queryexpr}, yyDollar[3].queryexprs...)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:291
		{
			yyVAL.queryexprs = []QueryExpression{yyDollar[1].queryexpr}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:293
		{
			yyVAL.queryexprs = append([]QueryExpression{yyDollar[1].queryexpr}, yyDollar[3].queryexprs...)
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:298
		{
			yyVAL.queryexpr = yyDollar[1].table
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:299
		{
			yyVAL.queryexpr = Table{Object: yyDollar[1].queryexpr}
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:300
		{
			yyVAL.queryexpr = Table{Object: yyDollar[1].queryexpr, Alias: yyDollar[2].identifier}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:302
		{
			yyVAL.queryexpr = Parentheses{Expr: yyDollar[2].queryexpr}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:307
		{
			yyVAL.queryexpr = yyDollar[1].identifier
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:311
		{
			yyVAL.queryexpr = Stdin{BaseExpr: NewBaseExpr(yyDollar[1].token), Stdin: yyDollar[1].token.Literal}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:316
		{
			yyVAL.table = Table{Object: yyDollar[1].queryexpr}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:320
		{
			yyVAL.table = Table{Object: yyDollar[1].queryexpr, Alias: yyDollar[2].identifier}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:324
		{
			yyVAL.table = Table{Object: yyDollar[1].queryexpr, As: yyDollar[2].token.Literal, Alias: yyDollar[3].identifier}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:329
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line grammar/block_query.y:335
		{
			yyVAL.queryexpr = nil
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:336
		{
			yyVAL.queryexpr = WithClause{With: yyDollar[1].token.Literal, InlineTables: yyDollar[2].queryexprs}
		}
	case 52:
		yyDollar = yyS[yypt-6 : yypt+1]
		//line grammar/block_query.y:340
		{
			yyVAL.queryexpr = InlineTable{Recursive: yyDollar[1].token, Name: yyDollar[2].identifier, As: yyDollar[3].token.Literal, Query: yyDollar[5].queryexpr.(SelectQuery)}
		}
	case 53:
		yyDollar = yyS[yypt-9 : yypt+1]
		//line grammar/block_query.y:344
		{
			yyVAL.queryexpr = InlineTable{Recursive: yyDollar[1].token, Name: yyDollar[2].identifier, Fields: yyDollar[4].queryexprs, As: yyDollar[6].token.Literal, Query: yyDollar[8].queryexpr.(SelectQuery)}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:351
		{
			yyVAL.queryexprs = []QueryExpression{yyDollar[1].queryexpr}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:355
		{
			yyVAL.queryexprs = append([]QueryExpression{yyDollar[1].queryexpr}, yyDollar[3].queryexprs...)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:361
		{
			yyVAL.queryexprs = []QueryExpression{yyDollar[1].identifier}
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:362
		{
			yyVAL.queryexprs = append([]QueryExpression{yyDollar[1].identifier}, yyDollar[3].queryexprs...)
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:367
		{
			yyVAL.queryexprs = []QueryExpression{yyDollar[1].queryexpr}
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:368
		{
			yyVAL.queryexprs = append([]QueryExpression{yyDollar[1].queryexpr}, yyDollar[3].queryexprs...)
		}
	case 60:
		yyDollar = yyS[yypt-4 : yypt+1]
		//line grammar/block_query.y:373
		{
			yyVAL.queryexpr = AnalyticFunction{BaseExpr: yyDollar[1].identifier.BaseExpr, Name: yyDollar[1].identifier.Literal, Args: yyDollar[3].queryexprs}
		}
	case 61:
		yyDollar = yyS[yypt-5 : yypt+1]
		//line grammar/block_query.y:377
		{
			yyVAL.queryexpr = AnalyticFunction{BaseExpr: NewBaseExpr(yyDollar[1].token), Name: yyDollar[1].token.Literal, Distinct: yyDollar[3].token, Args: yyDollar[4].queryexprs}
		}
	case 62:
		yyDollar = yyS[yypt-5 : yypt+1]
		//line grammar/block_query.y:381
		{
			yyVAL.queryexpr = AnalyticFunction{BaseExpr: NewBaseExpr(yyDollar[1].token), Name: yyDollar[1].token.Literal, Distinct: yyDollar[3].token, Args: []QueryExpression{yyDollar[4].queryexpr}}
		}
	case 63:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line grammar/block_query.y:404
		{
			yyVAL.queryexprs = nil
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:405
		{
			yyVAL.queryexprs = yyDollar[1].queryexprs
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:410
		{
			yyVAL.queryexpr = AllColumns{BaseExpr: NewBaseExpr(yyDollar[1].token)}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:417
		{
			yyVAL.queryexpr = RowValue{BaseExpr: NewBaseExpr(yyDollar[1].token), Value: ValueList{Values: yyDollar[2].queryexprs}}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:421
		{
			yyVAL.queryexpr = RowValue{BaseExpr: yyDollar[1].queryexpr.GetBaseExpr(), Value: yyDollar[1].queryexpr}
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:426
		{
			yyVAL.queryexprs = []QueryExpression{yyDollar[1].queryexpr}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:430
		{
			yyVAL.queryexprs = append([]QueryExpression{yyDollar[1].queryexpr}, yyDollar[3].queryexprs...)
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:436
		{
			yyVAL.queryexpr = Subquery{BaseExpr: NewBaseExpr(yyDollar[1].token), Query: yyDollar[2].queryexpr.(SelectQuery)}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:443
		{
			var item1 []QueryExpression
			var item2 []QueryExpression

			c1, ok := yyDollar[1].queryexpr.(Concat)
			if ok {
				item1 = c1.Items
			} else {
				item1 = []QueryExpression{yyDollar[1].queryexpr}
			}

			c2, ok := yyDollar[3].queryexpr.(Concat)
			if ok {
				item2 = c2.Items
			} else {
				item2 = []QueryExpression{yyDollar[3].queryexpr}
			}

			yyVAL.queryexpr = Concat{Items: append(item1, item2...)}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:467
		{
			yyVAL.queryexpr = Comparison{LHS: yyDollar[1].queryexpr, Operator: yyDollar[2].token.Literal, RHS: yyDollar[3].queryexpr}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:471
		{
			yyVAL.queryexpr = Comparison{LHS: yyDollar[1].queryexpr, Operator: yyDollar[2].token.Literal, RHS: yyDollar[3].queryexpr}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:475
		{
			yyVAL.queryexpr = Comparison{LHS: yyDollar[1].queryexpr, Operator: "=", RHS: yyDollar[3].queryexpr}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:479
		{
			yyVAL.queryexpr = Comparison{LHS: yyDollar[1].queryexpr, Operator: "=", RHS: yyDollar[3].queryexpr}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:483
		{
			yyVAL.queryexpr = In{In: yyDollar[2].token.Literal, LHS: yyDollar[1].queryexpr, Values: yyDollar[3].queryexpr}
		}
	case 77:
		yyDollar = yyS[yypt-4 : yypt+1]
		//line grammar/block_query.y:487
		{
			yyVAL.queryexpr = In{In: yyDollar[3].token.Literal, LHS: yyDollar[1].queryexpr, Values: yyDollar[4].queryexpr, Negation: yyDollar[2].token}
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:492
		{
			yyVAL.queryexpr = Exists{Exists: yyDollar[1].token.Literal, Query: yyDollar[2].queryexpr.(Subquery)}
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:498
		{
			yyVAL.queryexprs = []QueryExpression{yyDollar[1].queryexpr}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:502
		{
			yyVAL.queryexprs = append([]QueryExpression{yyDollar[1].queryexpr}, yyDollar[3].queryexprs...)
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:509
		{
			yyVAL.queryexpr = FieldReference{BaseExpr: yyDollar[1].identifier.BaseExpr, Column: yyDollar[1].identifier}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:513
		{
			yyVAL.queryexpr = FieldReference{BaseExpr: yyDollar[1].identifier.BaseExpr, View: yyDollar[1].identifier, Column: yyDollar[3].identifier}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:517
		{
			yyVAL.queryexpr = ColumnNumber{BaseExpr: yyDollar[1].identifier.BaseExpr, View: yyDollar[1].identifier, Number: value.NewIntegerFromString(yyDollar[3].token.Literal)}
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:523
		{
			yyVAL.queryexpr = Arithmetic{LHS: yyDollar[1].queryexpr, Operator: int('+'), RHS: yyDollar[3].queryexpr}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:524
		{
			yyVAL.queryexpr = Arithmetic{LHS: yyDollar[1].queryexpr, Operator: int('-'), RHS: yyDollar[3].queryexpr}
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:525
		{
			yyVAL.queryexpr = Arithmetic{LHS: yyDollar[1].queryexpr, Operator: int('*'), RHS: yyDollar[3].queryexpr}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:526
		{
			yyVAL.queryexpr = Arithmetic{LHS: yyDollar[1].queryexpr, Operator: int('/'), RHS: yyDollar[3].queryexpr}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:527
		{
			yyVAL.queryexpr = Arithmetic{LHS: yyDollar[1].queryexpr, Operator: int('%'), RHS: yyDollar[3].queryexpr}
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:528
		{
			yyVAL.queryexpr = UnaryArithmetic{Operand: yyDollar[2].queryexpr, Operator: yyDollar[1].token}
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:529
		{
			yyVAL.queryexpr = UnaryArithmetic{Operand: yyDollar[2].queryexpr, Operator: yyDollar[1].token}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:534
		{
			yyVAL.queryexpr = Logic{LHS: yyDollar[1].queryexpr, Operator: yyDollar[2].token, RHS: yyDollar[3].queryexpr}
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:538
		{
			yyVAL.queryexpr = Logic{LHS: yyDollar[1].queryexpr, Operator: yyDollar[2].token, RHS: yyDollar[3].queryexpr}
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:541
		{
			yyVAL.queryexpr = UnaryLogic{Operand: yyDollar[2].queryexpr, Operator: yyDollar[1].token}
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line grammar/block_query.y:542
		{
			yyVAL.queryexpr = UnaryLogic{Operand: yyDollar[2].queryexpr, Operator: yyDollar[1].token}
		}
	case 95:
		yyDollar = yyS[yypt-5 : yypt+1]
		//line grammar/block_query.y:547
		{
			yyVAL.queryexpr = AggregateFunction{BaseExpr: yyDollar[1].identifier.BaseExpr, Name: yyDollar[1].identifier.Literal, Distinct: yyDollar[3].token, Args: yyDollar[4].queryexprs}
		}
	case 96:
		yyDollar = yyS[yypt-5 : yypt+1]
		//line grammar/block_query.y:551
		{
			yyVAL.queryexpr = AggregateFunction{BaseExpr: NewBaseExpr(yyDollar[1].token), Name: yyDollar[1].token.Literal, Distinct: yyDollar[3].token, Args: yyDollar[4].queryexprs}
		}
	case 97:
		yyDollar = yyS[yypt-5 : yypt+1]
		//line grammar/block_query.y:555
		{
			yyVAL.queryexpr = AggregateFunction{BaseExpr: NewBaseExpr(yyDollar[1].token), Name: yyDollar[1].token.Literal, Distinct: yyDollar[3].token, Args: yyDollar[4].queryexprs}
		}
	case 98:
		yyDollar = yyS[yypt-5 : yypt+1]
		//line grammar/block_query.y:559
		{
			yyVAL.queryexpr = AggregateFunction{BaseExpr: NewBaseExpr(yyDollar[1].token), Name: yyDollar[1].token.Literal, Distinct: yyDollar[3].token, Args: []QueryExpression{yyDollar[4].queryexpr}}
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:566
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:570
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:574
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:578
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:582
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:586
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:590
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:594
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:598
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:602
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:606
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:610
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:614
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:618
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:622
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:626
		{
			yyVAL.identifier = Identifier{BaseExpr: NewBaseExpr(yyDollar[1].token), Literal: yyDollar[1].token.Literal, Quoted: yyDollar[1].token.Quoted}
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:632
		{
			yyVAL.queryexpr = NewNullValueFromString(yyDollar[1].token.Literal)
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:636
		{
			yyVAL.variable = Variable{BaseExpr: NewBaseExpr(yyDollar[1].token), Name: yyDollar[1].token.Literal}
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:643
		{
			yyVAL.variables = []Variable{yyDollar[1].variable}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:646
		{
			yyVAL.variables = append([]Variable{yyDollar[1].variable}, yyDollar[3].variables...)
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:651
		{
			yyVAL.queryexpr = VariableSubstitution{Variable: yyDollar[1].variable, Value: yyDollar[3].queryexpr}
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:658
		{
			yyVAL.queryexpr = NewTernaryValueFromString(yyDollar[1].token.Literal)
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:664
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:665
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:666
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:667
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:668
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:669
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:670
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:671
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:672
		{
			yyVAL.queryexpr = yyDollar[1].variable
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:673
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line grammar/block_query.y:674
		{
			yyVAL.queryexpr = Parentheses{Expr: yyDollar[2].queryexpr}
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:679
		{
			yyVAL.queryexpr = NewStringValue(yyDollar[1].token.Literal)
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:683
		{
			yyVAL.queryexpr = NewIntegerValueFromString(yyDollar[1].token.Literal)
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:687
		{
			yyVAL.queryexpr = NewFloatValueFromString(yyDollar[1].token.Literal)
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:691
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:695
		{
			yyVAL.queryexpr = NewDatetimeValueFromString(yyDollar[1].token.Literal)
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:699
		{
			yyVAL.queryexpr = yyDollar[1].queryexpr
		}
	case 138:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line grammar/block_query.y:705
		{
			yyVAL.token = Token{}
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:706
		{
			yyVAL.token = yyDollar[1].token
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line grammar/block_query.y:718
		{
			yyDollar[1].token.Token = '='
			yyVAL.token = yyDollar[1].token
		}
	}
	goto yystack /* stack new state and value */
}
